### ISSUE TITLE
Hey man, I saw your post on stackoverflow that wasn't solved so i wanted to ask If you resolved it yourself

### ISSUE THREAD

**Issue by akisha009** [SebastiaanTheCoder/SimpleCLI#1]
First of all I am sorry for randomly contacting you and asking about some stackoverflow post.
It's about this post :
https://stackoverflow.com/questions/75496416/discord-rate-limiting-while-only-sending-1-request-per-minute?rq=2
I am having the exact same problem as you and I would really appreciate if you could tell me what did you do (if you resolved it).
Thanks

**Comment by SebastiaanTheCoder** [comment]
Hey,
This was a long while ago but I had some time and did some digging. Unfortunately I remember not being able to fix this issue and sticking to updating the channel name every 5 minutes. This is because for some reason discord rate limits channel updates to 2 every 10 minutes.
[https://stackoverflow.com/questions/62103163/how-often-can-i-rename-discord-channels-name](url) 
I even tried using the raw api endpoints and got the same result. So you are unfortunately going to have to find another way to accomplish this.

Have a nice day and if you need any other questions you can find my email in my account details I think.
Sebastiaan
